### ISSUE TITLE
Need to set platform on Apple M1 MacOS

### ISSUE THREAD

**Issue by jgracin** [1and1/vscode-remote-try-clojure#1]
Hi!

Thanks for the project!

Just FYI, in order to run this on MacOS with M1, I had to change the Dockerfile to include platform, like this:
`FROM --platform=linux/amd64 clojure:openjdk-8-lein-2.9.1`

Otherwise, I was getting an error saying: "failed to create LLB definition: no match for platform".

**Comment by alitari** [comment]
Thx for the feedback. :bouquet:
